services:
  - type: web
    name: yt-dlp-transcript-api
    env: python
    runtime: python-3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11